"""
Last-day quips. Prepended to a reminder only when the last-day boost is
what made it fire.

This module is imported lazily, inside the quip function, so a run with no
last-day notices never opens or parses it. Editing this list touches no bot
logic -- replace the tuple and redeploy.

Rules for lines added here:
  - one or two short lines, under ~120 characters
  - no leading or trailing blank lines
  - avoid characters WhatsApp treats as markup: * _ ~ ```
  - dry, never mean about the person -- the people most likely to be behind
    are the ones a harsh line lands worst on

Aim for enough lines that a group does not see a repeat within a term. Sixty
is plenty; a hundred is comfortable.
"""

QUIPS: tuple[str, ...] = (
  "A nudge. Not a judgement, just a nudge.",
  "Panic is scheduled for later. Beat the rush.",
  "I stop the moment this is handled. That's the whole arrangement.",
  "A thumbs-up reaction does not count. Nice try.",
  "Somewhere a responsible adult is already done. Strange feeling, isn't it.",
  "Quick one — costs less time than remembering it does.",
  "This one's been waiting patiently. Its patience is finite.",
  "Overfitting to Instagram, underfitting to everything else.",
  "The machines are learning. This is still pending.",
  "Karna toh hai hi. Timing tumhari choice hai.",
  "Small thing, still pending. Let's fix that.",
  "The pipeline ran. The model converged. You're the bottleneck.",
  "One item. Then peace.",
  "Group mein poochne se pehle khud kar lo.",
  "Aaj kar lo, kal free.",
  "Nothing improves by staying in drafts.",
  "An MTech in AI, and this is still fully manual. Poetic.",
  "Your attention mechanism has drifted. Recalibrate.",
  "This has been 'almost done' for a suspiciously long while.",
  "Still open. Still waiting. Still yours.",
  "I have excellent memory and absolutely no shame.",
  "The Wi-Fi will fail at the worst possible moment. Plan accordingly.",
  "Your excuses are beautifully structured. Frame one.",
  "Legend speaks of someone doing it early. Unverified.",
  "Time is a construct. Calendars are not.",
  "You have time. You do not have infinite time.",
  "Yes, now. Not 'now-ish'.",
  "Perfection is a good excuse and a bad plan.",
  "Last day. Even the model you fine-tuned overnight converged faster than this.",
  "Start badly. Momentum handles the rest.",
  "This is the third-nicest way I could have put it.",
  "The universe is indifferent. The calendar is not.",
  "Gradient descent works because it takes a step. Take one.",
  "Deadline's today. Your submission is the only thing in this pipeline that hasn't been automated yet.",
  "Deadline today. You've read three papers on optimization. Try applying one.",
  "The group is quiet. The calendar is not.",
  "Waiting for the right mood is a scheduling error.",
  "The thinking is done. Only the doing is left.",
  "Consider this the friendly version.",
  "That's the reminder. That's the entire content.",
  "Today. Attendance ka jugaad chal jayega, deadline ka nahi.",
  "The version you have is better than the one you're imagining.",
  "Abhi kar lo, raat ko chain se so jaoge.",
  "Low effort, high relief. Rare combination.",
  "Reading this is not the same as doing this.",
  "Twenty focused minutes. Bas itna.",
  "Everyone assumes someone else is further behind. Statistically, no.",
  "You already know this one. It just needs doing.",
  "Good news: after this you stop thinking about it. Either way.",
  "This is easier now than it will be later. It always is.",
  "Being ignored beautifully, as always.",
  "Chhoti cheez hai — reh gayi toh badi ban jaayegi.",
  "Deadline today. You're doing an MTech in AI and still doing this manually. Poetic.",
  "Someone here already handled it. They are insufferably calm.",
  "The reminder was the easy part. Over to you.",
  "The clock has no opinion about your reasons.",
  "Swipe it away if you like. I'll be back.",
  "AI will not take your job. This backlog might take your weekend.",
  "Half-done today beats perfect never.",
  "Putting this on today, not on someday.",
  "No model required here. Just a human, briefly.",
  "Today's the day. GPT can write your abstract, not your regret.",
  "Reminder aaya hai matlab abhi bhi time hai.",
  "Bas paanch minute ka dhyaan chahiye, aur kuch nahi.",
  "No early stopping on this one.",
  "Chhota kaam hai. Isiliye har baar reh jaata hai.",
  "It's on the list. Lists don't clear themselves.",
  "Bold approach so far. Results pending.",
  "Finish it and go back to your actual life.",
  "Everything else in your stack runs on schedule. This doesn't.",
  "Last day. Somewhere a batch job is finishing on time. Be inspired.",
  "Close the twelve tabs. Keep one.",
  "Last day. The model trained. The pipeline ran. Only you are still idle.",
  "Smaller than it looks from here. Most things are.",
  "No drama needed. Just this one thing.",
  "Do it now, quietly, and be done.",
  "GPT se plan bana lo, karna toh khud hi padega.",
  "Deadline's today. No epochs left, no early stopping.",
  "Your model generalises better than your excuses.",
  "Not urgent yet — which is exactly why now is a good time.",
  "You automate pipelines for a living. Try automating this.",
  "Last day. AI will not take your job. This deadline might take your CGPA.",
  "Dekh liya? Ab kar bhi lo.",
  "Even a random baseline does something.",
  "This reminder shows up more reliably than most of us.",
  "Prompt engineering will not help if nobody presses go.",
  "nth time I'm mentioning this. There will be a n+1.",
  "Hope is not a strategy, though it remains very popular.",
  "Haan, yeh reminder tumhare liye hi hai.",
  "Latency between knowing and doing is unusually high today.",
  "'Baad mein karta hoon' ka baad mein aa gaya.",
  "Automate the rest. This one still needs a human in the loop.",
  "A cron job somewhere is doing its part right now. Be inspired.",
  "Ten minutes now, zero panic later.",
  "You've handled harder things quietly this semester. This too.",
  "Your future self is watching. Mildly concerned.",
  "Marking this read is not the same as acting on it.",
  "Future you is quietly hoping.",
  "Deadline's today. Your loss function is not going down on its own.",
  "Aaj thoda, taaki baad mein bahut na karna pade.",
  "Last day. The machines are learning. You are pending.",
  "Plan B is hope. Plan A is still available.",
  "Last-minute heroics build character. You have enough character.",
  "Handle it while it's still a task and not a problem.",
  "Bas ek kaam. Phir chill.",
  "Do it now and earn the right to relax convincingly.",
  "Training runs finish on time. Human loops stall. Curious.",
  "AI can do a great deal. It cannot do this on your behalf.",
  "Very impressive commitment to the last possible hour.",
  "One tab, one task, go.",
  "Nothing says confidence like starting at 11:47 pm.",
  "This message will keep returning until something happens.",
)
